### PR TITLE
Update Corpus Info for Mixtec

### PR DESCRIPTION
**Pull request by ftshijt**
Hi, I'm wondering how can I upload the data to the server, or do I simply sent it to you.

### CODE REVIEW

**Comment by jtrmal** [comment]
just remove the "\<WIP\>" and I review and merge
y.

**Comment by jtrmal** [comment]
Oh, if there is an issue with the data archives, please prepare the pack again and send me a download link
y.

**Comment by ftshijt** [comment]
> Oh, if there is an issue with the data archives, please prepare the pack again and send me a download link
> y.

Hi, is it available to add on a new tar? I have it at `/export/c04/jiatong/data/openslr_yoloxochitl/Yoloxochitl-Mixtec-Manifest.tgz` at grid machine.

**Comment by jtrmal** [comment]
OK, done -- please let me know what the file contains (similarly to:
```
file: Yoloxochitl-Mixtec-Data.tgz Yolóxochitl Mixtec Speech and
Transcription
```
)

**Comment by jtrmal** [comment]
Ah, I see you did that already. Great job! You understood the workflow better than myself :)

**Pull request merged**
