### PR TITLE
update of info.txt and about.html requested

### PR DESCRIPTION
**Pull request by larocaroja**

### CODE REVIEW

**Comment by larocaroja** [comment]
ignore 2nd~6th commits, and for the last 3 commits, I replaced the previous tgz with the new one.(you didn't ask for it tho) Just reject them if you're gonna do it yourself. Thanks!

**Comment by jtrmal** [comment]
thanks!

**Comment by jtrmal** [comment]
can you please remove the binaries? I will replace them manually. Data management has a different workflow than metadata management

**Comment by larocaroja** [comment]
just reverted all the commits concerning binaries!

**Comment by jtrmal** [comment]
thanks, merging...

**Pull request merged**
