### PR TITLE
Add Speech Translation Resources, Totonac Resources to Puebla-Nahuatl

### PR DESCRIPTION
**Pull request by ftshijt**
Hi, we recently prepared the resources for speech translation and resource for another language (Totonac) for Puebla-Nahuatl corpus.

The relevant files are at CLSP grid

```
- /export/c04/jiatong/data/openslr_puebla_nahuatl/Totonac_Corpus.tgz
- /export/c04/jiatong/data/openslr_puebla_nahuatl/SpeechTranslation_Nahuatl_Manifest.tgz
```

### CODE REVIEW

**Comment by jtrmal** [comment]
Out of curiosity -- why not have Totonac as a separate resource?

**Comment by ftshijt** [comment]
> Out of curiosity -- why not have Totonac as a separate resource?

Thanks for pointing it out. Let's do it in a separate manner. I will prepare the intro shortly.

**Comment by jtrmal** [comment]
thanks
y.

**Comment by jtrmal** [comment]
I'm closing this, as I have added the translation manually in a separate commit
y.

**Pull request closed without merging**
